import csv
f= open("code.txt","w+")
file  = open("logic.csv")
type(file)
csvreader = csv.reader(file)
next(csvreader)
a = 0
b = 0
c = 1

f.write("//Block %d\n" % c)
for row in csvreader:
    if a == 0:
        f.write("while(receive16Bit() != %s);\n" % row[2])
        a = 1
    else:
        f.write("send16Bit(%s);\n" % row[2])
        a = 0
    b = b+1
    if(b == 18):
        b = 0
        f.write("\n")
        c = c + 1
        f.write("//Block %d\n" % c)
f.close()

def convert2gba():
    # input
   print("Input 7 character String for Conversion to Gen 3 Character code")
   a = ""
   b = ""
   c = ""
   d = ""
   e = ""
   f = ""
   g = ""
   input1 = input()
   length_input = len(input1)
   print("length of String: %s\n" % length_input)
   if(length_input == 1):
            a = input1
   elif(length_input == 2):
            a,b = input1
   elif(length_input == 3):
            a,b,c = input1
   elif(length_input == 4):
            a,b,c,d = input1
   elif(length_input == 5):
            a,b,c,d,e = input1
   elif(length_input == 6):
            a,b,c,d,e,f = input1
   elif(length_input == 7):
            a,b,c,d,e,f,g = input1
   else:
            print("input error: length")
   match a:
            case "A": print("BB ")
            case "B": print("BC ")
            case "C": print("BD ")
            case "D": print("BE ")
            case "E": print("BF ")
            case "F": print("C0 ")
            case "G": print("C1 ")
            case "H": print("C2 ")
            case "I": print("C3 ")
            case "J": print("C4 ")
            case "K": print("C5 ")
            case "L": print("C6 ")
            case "M": print("C7 ")
            case "N": print("C8 ")
            case "O": print("C9 ")
            case "P": print("CA ")
            case "Q": print("CB ")
            case "R": print("CC ")
            case "S": print("CD ")
            case "T": print("CE ")
            case "U": print("CF ")
            case "V": print("D0 ")
            case "W": print("D1 ")
            case "X": print("D2 ")
            case "Y": print("D3 ")
            case "Z": print("D4 ")
            case "a": print("D5 ")
            case "b": print("D6 ")
            case "c": print("D7 ")
            case "d": print("D8 ")
            case "e": print("D9 ")
            case "f": print("DA ")
            case "g": print("DB ")
            case "h": print("DC ")
            case "i": print("DD ")
            case "j": print("DE ")
            case "k": print("DF ")
            case "l": print("E0 ")
            case "m": print("E1 ")
            case "n": print("E2 ")
            case "o": print("E3 ")
            case "p": print("E4 ")
            case "q": print("E5 ")
            case "r": print("E6 ")
            case "s": print("E7 ")
            case "t": print("E8 ")
            case "u": print("E9 ")
            case "v": print("EA ")
            case "w": print("EB ")
            case "x": print("EC ")
            case "y": print("ED ")
            case "z": print("EE ")
            case "Ä": print("F1 ")
            case "Ö": print("F2 ")
            case "Ü": print("F3 ")
            case "ä": print("F4 ")
            case "ö": print("F5 ")
            case "ü": print("F6 ")
            case "0": print("A1 ")
            case "1": print("A2 ")
            case "2": print("A3 ")
            case "3": print("A4 ")
            case "4": print("A5 ")
            case "5": print("A6 ")
            case "6": print("A7 ")
            case "7": print("A8 ")
            case "8": print("A9 ")
            case "9": print("AA ")
        
   match b:
        case "A": print("BB ")
        case "B": print("BC ")
        case "C": print("BD ")
        case "D": print("BE ")
        case "E": print("BF ")
        case "F": print("C0 ")
        case "G": print("C1 ")
        case "H": print("C2 ")
        case "I": print("C3 ")
        case "J": print("C4 ")
        case "K": print("C5 ")
        case "L": print("C6 ")
        case "M": print("C7 ")
        case "N": print("C8 ")
        case "O": print("C9 ")
        case "P": print("CA ")
        case "Q": print("CB ")
        case "R": print("CC ")
        case "S": print("CD ")
        case "T": print("CE ")
        case "U": print("CF ")
        case "V": print("D0 ")
        case "W": print("D1 ")
        case "X": print("D2 ")
        case "Y": print("D3 ")
        case "Z": print("D4 ")
        case "a": print("D5 ")
        case "b": print("D6 ")
        case "c": print("D7 ")
        case "d": print("D8 ")
        case "e": print("D9 ")
        case "f": print("DA ")
        case "g": print("DB ")
        case "h": print("DC ")
        case "i": print("DD ")
        case "j": print("DE ")
        case "k": print("DF ")
        case "l": print("E0 ")
        case "m": print("E1 ")
        case "n": print("E2 ")
        case "o": print("E3 ")
        case "p": print("E4 ")
        case "q": print("E5 ")
        case "r": print("E6 ")
        case "s": print("E7 ")
        case "t": print("E8 ")
        case "u": print("E9 ")
        case "v": print("EA ")
        case "w": print("EB ")
        case "x": print("EC ")
        case "y": print("ED ")
        case "z": print("EE ")
        case "Ä": print("F1 ")
        case "Ö": print("F2 ")
        case "Ü": print("F3 ")
        case "ä": print("F4 ")
        case "ö": print("F5 ")
        case "ü": print("F6 ")
        case "0": print("A1 ")
        case "1": print("A2 ")
        case "2": print("A3 ")
        case "3": print("A4 ")
        case "4": print("A5 ")
        case "5": print("A6 ")
        case "6": print("A7 ")
        case "7": print("A8 ")
        case "8": print("A9 ")
        case "9": print("AA ")

   match c:
        case "A": print("BB ")
        case "B": print("BC ")
        case "C": print("BD ")
        case "D": print("BE ")
        case "E": print("BF ")
        case "F": print("C0 ")
        case "G": print("C1 ")
        case "H": print("C2 ")
        case "I": print("C3 ")
        case "J": print("C4 ")
        case "K": print("C5 ")
        case "L": print("C6 ")
        case "M": print("C7 ")
        case "N": print("C8 ")
        case "O": print("C9 ")
        case "P": print("CA ")
        case "Q": print("CB ")
        case "R": print("CC ")
        case "S": print("CD ")
        case "T": print("CE ")
        case "U": print("CF ")
        case "V": print("D0 ")
        case "W": print("D1 ")
        case "X": print("D2 ")
        case "Y": print("D3 ")
        case "Z": print("D4 ")
        case "a": print("D5 ")
        case "b": print("D6 ")
        case "c": print("D7 ")
        case "d": print("D8 ")
        case "e": print("D9 ")
        case "f": print("DA ")
        case "g": print("DB ")
        case "h": print("DC ")
        case "i": print("DD ")
        case "j": print("DE ")
        case "k": print("DF ")
        case "l": print("E0 ")
        case "m": print("E1 ")
        case "n": print("E2 ")
        case "o": print("E3 ")
        case "p": print("E4 ")
        case "q": print("E5 ")
        case "r": print("E6 ")
        case "s": print("E7 ")
        case "t": print("E8 ")
        case "u": print("E9 ")
        case "v": print("EA ")
        case "w": print("EB ")
        case "x": print("EC ")
        case "y": print("ED ")
        case "z": print("EE ")
        case "Ä": print("F1 ")
        case "Ö": print("F2 ")
        case "Ü": print("F3 ")
        case "ä": print("F4 ")
        case "ö": print("F5 ")
        case "ü": print("F6 ")
        case "0": print("A1 ")
        case "1": print("A2 ")
        case "2": print("A3 ")
        case "3": print("A4 ")
        case "4": print("A5 ")
        case "5": print("A6 ")
        case "6": print("A7 ")
        case "7": print("A8 ")
        case "8": print("A9 ")
        case "9": print("AA ")

   match d:
        case "A": print("BB ")
        case "B": print("BC ")
        case "C": print("BD ")
        case "D": print("BE ")
        case "E": print("BF ")
        case "F": print("C0 ")
        case "G": print("C1 ")
        case "H": print("C2 ")
        case "I": print("C3 ")
        case "J": print("C4 ")
        case "K": print("C5 ")
        case "L": print("C6 ")
        case "M": print("C7 ")
        case "N": print("C8 ")
        case "O": print("C9 ")
        case "P": print("CA ")
        case "Q": print("CB ")
        case "R": print("CC ")
        case "S": print("CD ")
        case "T": print("CE ")
        case "U": print("CF ")
        case "V": print("D0 ")
        case "W": print("D1 ")
        case "X": print("D2 ")
        case "Y": print("D3 ")
        case "Z": print("D4 ")
        case "a": print("D5 ")
        case "b": print("D6 ")
        case "c": print("D7 ")
        case "d": print("D8 ")
        case "e": print("D9 ")
        case "f": print("DA ")
        case "g": print("DB ")
        case "h": print("DC ")
        case "i": print("DD ")
        case "j": print("DE ")
        case "k": print("DF ")
        case "l": print("E0 ")
        case "m": print("E1 ")
        case "n": print("E2 ")
        case "o": print("E3 ")
        case "p": print("E4 ")
        case "q": print("E5 ")
        case "r": print("E6 ")
        case "s": print("E7 ")
        case "t": print("E8 ")
        case "u": print("E9 ")
        case "v": print("EA ")
        case "w": print("EB ")
        case "x": print("EC ")
        case "y": print("ED ")
        case "z": print("EE ")
        case "Ä": print("F1 ")
        case "Ö": print("F2 ")
        case "Ü": print("F3 ")
        case "ä": print("F4 ")
        case "ö": print("F5 ")
        case "ü": print("F6 ")
        case "0": print("A1 ")
        case "1": print("A2 ")
        case "2": print("A3 ")
        case "3": print("A4 ")
        case "4": print("A5 ")
        case "5": print("A6 ")
        case "6": print("A7 ")
        case "7": print("A8 ")
        case "8": print("A9 ")
        case "9": print("AA ")
   match e:
        case "A": print("BB ")
        case "B": print("BC ")
        case "C": print("BD ")
        case "D": print("BE ")
        case "E": print("BF ")
        case "F": print("C0 ")
        case "G": print("C1 ")
        case "H": print("C2 ")
        case "I": print("C3 ")
        case "J": print("C4 ")
        case "K": print("C5 ")
        case "L": print("C6 ")
        case "M": print("C7 ")
        case "N": print("C8 ")
        case "O": print("C9 ")
        case "P": print("CA ")
        case "Q": print("CB ")
        case "R": print("CC ")
        case "S": print("CD ")
        case "T": print("CE ")
        case "U": print("CF ")
        case "V": print("D0 ")
        case "W": print("D1 ")
        case "X": print("D2 ")
        case "Y": print("D3 ")
        case "Z": print("D4 ")
        case "a": print("D5 ")
        case "b": print("D6 ")
        case "c": print("D7 ")
        case "d": print("D8 ")
        case "e": print("D9 ")
        case "f": print("DA ")
        case "g": print("DB ")
        case "h": print("DC ")
        case "i": print("DD ")
        case "j": print("DE ")
        case "k": print("DF ")
        case "l": print("E0 ")
        case "m": print("E1 ")
        case "n": print("E2 ")
        case "o": print("E3 ")
        case "p": print("E4 ")
        case "q": print("E5 ")
        case "r": print("E6 ")
        case "s": print("E7 ")
        case "t": print("E8 ")
        case "u": print("E9 ")
        case "v": print("EA ")
        case "w": print("EB ")
        case "x": print("EC ")
        case "y": print("ED ")
        case "z": print("EE ")
        case "Ä": print("F1 ")
        case "Ö": print("F2 ")
        case "Ü": print("F3 ")
        case "ä": print("F4 ")
        case "ö": print("F5 ")
        case "ü": print("F6 ")
        case "0": print("A1 ")
        case "1": print("A2 ")
        case "2": print("A3 ")
        case "3": print("A4 ")
        case "4": print("A5 ")
        case "5": print("A6 ")
        case "6": print("A7 ")
        case "7": print("A8 ")
        case "8": print("A9 ")
        case "9": print("AA ")
   match f:
        case "A": print("BB ")
        case "B": print("BC ")
        case "C": print("BD ")
        case "D": print("BE ")
        case "E": print("BF ")
        case "F": print("C0 ")
        case "G": print("C1 ")
        case "H": print("C2 ")
        case "I": print("C3 ")
        case "J": print("C4 ")
        case "K": print("C5 ")
        case "L": print("C6 ")
        case "M": print("C7 ")
        case "N": print("C8 ")
        case "O": print("C9 ")
        case "P": print("CA ")
        case "Q": print("CB ")
        case "R": print("CC ")
        case "S": print("CD ")
        case "T": print("CE ")
        case "U": print("CF ")
        case "V": print("D0 ")
        case "W": print("D1 ")
        case "X": print("D2 ")
        case "Y": print("D3 ")
        case "Z": print("D4 ")
        case "a": print("D5 ")
        case "b": print("D6 ")
        case "c": print("D7 ")
        case "d": print("D8 ")
        case "e": print("D9 ")
        case "f": print("DA ")
        case "g": print("DB ")
        case "h": print("DC ")
        case "i": print("DD ")
        case "j": print("DE ")
        case "k": print("DF ")
        case "l": print("E0 ")
        case "m": print("E1 ")
        case "n": print("E2 ")
        case "o": print("E3 ")
        case "p": print("E4 ")
        case "q": print("E5 ")
        case "r": print("E6 ")
        case "s": print("E7 ")
        case "t": print("E8 ")
        case "u": print("E9 ")
        case "v": print("EA ")
        case "w": print("EB ")
        case "x": print("EC ")
        case "y": print("ED ")
        case "z": print("EE ")
        case "Ä": print("F1 ")
        case "Ö": print("F2 ")
        case "Ü": print("F3 ")
        case "ä": print("F4 ")
        case "ö": print("F5 ")
        case "ü": print("F6 ")
        case "0": print("A1 ")
        case "1": print("A2 ")
        case "2": print("A3 ")
        case "3": print("A4 ")
        case "4": print("A5 ")
        case "5": print("A6 ")
        case "6": print("A7 ")
        case "7": print("A8 ")
        case "8": print("A9 ")
        case "9": print("AA ")
   match g:
        case "A": print("BB ")
        case "B": print("BC ")
        case "C": print("BD ")
        case "D": print("BE ")
        case "E": print("BF ")
        case "F": print("C0 ")
        case "G": print("C1 ")
        case "H": print("C2 ")
        case "I": print("C3 ")
        case "J": print("C4 ")
        case "K": print("C5 ")
        case "L": print("C6 ")
        case "M": print("C7 ")
        case "N": print("C8 ")
        case "O": print("C9 ")
        case "P": print("CA ")
        case "Q": print("CB ")
        case "R": print("CC ")
        case "S": print("CD ")
        case "T": print("CE ")
        case "U": print("CF ")
        case "V": print("D0 ")
        case "W": print("D1 ")
        case "X": print("D2 ")
        case "Y": print("D3 ")
        case "Z": print("D4 ")
        case "a": print("D5 ")
        case "b": print("D6 ")
        case "c": print("D7 ")
        case "d": print("D8 ")
        case "e": print("D9 ")
        case "f": print("DA ")
        case "g": print("DB ")
        case "h": print("DC ")
        case "i": print("DD ")
        case "j": print("DE ")
        case "k": print("DF ")
        case "l": print("E0 ")
        case "m": print("E1 ")
        case "n": print("E2 ")
        case "o": print("E3 ")
        case "p": print("E4 ")
        case "q": print("E5 ")
        case "r": print("E6 ")
        case "s": print("E7 ")
        case "t": print("E8 ")
        case "u": print("E9 ")
        case "v": print("EA ")
        case "w": print("EB ")
        case "x": print("EC ")
        case "y": print("ED ")
        case "z": print("EE ")
        case "Ä": print("F1 ")
        case "Ö": print("F2 ")
        case "Ü": print("F3 ")
        case "ä": print("F4 ")
        case "ö": print("F5 ")
        case "ü": print("F6 ")
        case "0": print("A1 ")
        case "1": print("A2 ")
        case "2": print("A3 ")
        case "3": print("A4 ")
        case "4": print("A5 ")
        case "5": print("A6 ")
        case "6": print("A7 ")
        case "7": print("A8 ")
        case "8": print("A9 ")
        case "9": print("AA ")
    # output
   print(input1)
   print("\n")

def convert2readable():
   print("Input character code conversion")
   a = ""
   input1 = input()
   a = input1
   match a:
            case "BB": print("A") 
            case "BC": print("B") 
            case "BD": print("C") 
            case "BE": print("D") 
            case "BF": print("E") 
            case "C0": print("F") 
            case "C1": print("G") 
            case "C2": print("H") 
            case "C3": print("I") 
            case "C4": print("J") 
            case "C5": print("K") 
            case "C6": print("L") 
            case "C7": print("M") 
            case "C8": print("N") 
            case "C9": print("O") 
            case "CA": print("P") 
            case "CB": print("Q") 
            case "CC": print("R") 
            case "CD": print("S") 
            case "CE": print("T") 
            case "CF": print("U") 
            case "D0": print("V") 
            case "D1": print("W") 
            case "D2": print("X") 
            case "D3": print("Y") 
            case "D4": print("Z") 
            case "D5": print("a") 
            case "D6": print("b") 
            case "D7": print("c") 
            case "D8": print("d") 
            case "D9": print("e") 
            case "DA": print("f") 
            case "DB": print("g") 
            case "DC": print("h") 
            case "DD": print("i") 
            case "DE": print("j") 
            case "DF": print("k") 
            case "E0": print("l") 
            case "E1": print("m") 
            case "E2": print("n") 
            case "E3": print("o") 
            case "E4": print("p") 
            case "E5": print("q") 
            case "E6": print("r") 
            case "E7": print("s") 
            case "E8": print("t") 
            case "E9": print("u") 
            case "EA": print("v") 
            case "EB": print("w") 
            case "EC": print("x") 
            case "ED": print("y") 
            case "EE": print("z") 
            case "F1": print("Ä") 
            case "F2": print("Ö") 
            case "F3": print("Ü") 
            case "F4": print("ä") 
            case "F5": print("ö") 
            case "F6": print("ü") 
            case "A1": print("0") 
            case "A2": print("1") 
            case "A3": print("2") 
            case "A4": print("3") 
            case "A5": print("4") 
            case "A6": print("5") 
            case "A7": print("6") 
            case "A8": print("7") 
            case "A9": print("8") 
            case "AA": print("9")

while(1):
    print("Select mode:\n1    Convert to GBA\n2    Convert to readable text")
    input1 = input()
    if(input1=="1"):
        while(1):
            convert2gba()
    elif(input1=="2"):
        while(1):
            convert2readable()
    else:
        print("No valid mode selected")
